### PR TITLE
Preview modal

### PR DESCRIPTION
**Pull request by AB1908**
Implements #53

### CODE REVIEW

**Comment by AB1908** [comment]
VSCode has different formatting styles. What should I use to avoid changing whitespaces? Do we want to use something like `prettier`?

**Comment by mProjectsCode** [comment]
> Do we want to use something like `prettier`?
Never worked with that, but I can try setting it up

**Comment by AB1908** [comment]
Ah shite I screwed up the merge

**Comment by AB1908** [comment]
Lmfao I broke it. I'll spend some time cleaning it up.

**Comment by AB1908** [comment]
Ok looks like it works. I really wish I knew how to write tests for these lol.

**Comment by mProjectsCode** [comment]
@AB1908 if you want you can look over this again to see if I broke something

**Comment by AB1908** [comment]
I think it looks good. I forgot to pull in your changes earlier and half baked my merge. I'll try and pull this down to test locally.

**Comment by AB1908** [comment]
There were some modal closing problems. I'll push a fix later this week hopefully.

**Pull request merged**
