### PR TITLE
Added support for Moby Games API

### PR DESCRIPTION
**Pull request by ltctceplrm**
It needs authentication through an API key but you get those by making a free account.

This PR solves #76 and its duplicate #118. Potentially also solves #20 if Moby Games is satisfactory for the OP.

### CODE REVIEW

**Comment by ltctceplrm** [comment]
I think it would be beneficial if it was possible to disable certain APIs from media types, for instance if you don't want to make a Moby Games or Omdb APIkey but you want to use the Steam API to add games then currently it would give an authentication error for either one of them and error out. Do you think such an option would be feasible and useful?

**Comment by ltctceplrm** [comment]
Here's what it could look like in the settings:


Currently I've only added a toggle for media types where there are multiple APIs you can choose from.

**Comment by mProjectsCode** [comment]
Not a bad idea, though the different media types should be separated by sub headings imo.

**Review by mProjectsCode — APPROVED** [review]
Your PR looks good.

**Comment by mProjectsCode** [comment]
I think it would be best if you made a separate PR for the API media type settings.

**Comment by ltctceplrm** [comment]
Good point about separating it with sub headings per media type instead of per API, it would be clearer like that.


I haven't progressed far enough to make it into a PR yet though, I've added the settings but they don't do anything yet until I figure out the best way to have MediaDbSearchModal only select the ones that are toggled. I'm not very good proficient with Typescript so I'm currently stuck on that part

**Pull request merged**
